image: "nikolaik/python-nodejs:python3.7-nodejs13"

stages:
  - test

dev:
  stage: test 
  only:
    - master
  before_script:
    - npm install -g serverless
    - npm install  serverless-python-requirements

  script:
    - serverless deploy --stage dev --region ap-south-1 --verbose
